More metadata info & Support download video
15cm/twitter-favorites-archive pull request #3
Opened 2022-11-09 15:16 UTC by chu-shen

1. 添加了更多元数据信息。不知道是不是keywords添加错了，PhotoPrism并没有自动添加为标签🥲
2. 支持下载视频及其图片

2022-11-10 02:54 UTC, 15cm commented
`hashtags=$(jq -r '.entities.hashtags[].text' "$meta_file")` 解析出来长什么样子？
1. `#tag1, #tag2`
2. `tag1, tag2`
3. [tag1, tag2]
4. ...

我看 exiftool 有用来指定多个 keyword 的选项 https://exiftool.org/forum/index.php?topic=9054.0 ，然后这个还得配合看 PhotoPrism 用的 library 是怎么读的。要是目前不工作的话我倾向于先不加的 metadata 里，不然读代码/readme 的人不知道这个 feature 的支持情况

2022-11-10 05:11 UTC, chu-shen commented
### 解析结果

```shell
root@1c91b351356c:/app/output/2022/11/1589934547432779777# jq -r '.entities.hashtags[].text' tweet.json
Cyberpunk2077
サイバーパンクエッジランナーズ
lucy
root@1c91b351356c:/app/output/2022/11/1589934547432779777# exiftool -keywords 1589934547432779800-0.jpg
Keywords                        : Cyberpunk2077.サイバーパンクエッジランナーズ.lucy


root@1c91b351356c:/app/output/2022/11/1589317103383113729# jq -r '.entities.hashtags[].text' tweet.json
NovelAIDiffusion
NovelAI
root@1c91b351356c:/app/output/2022/11/1589317103383113729# exiftool -keywords 1589317103383113700-0.jpg
Keywords                        : NovelAIDiffusion.NovelAI
```

### PhotoPrism显示结果

[结果写入了「关键词」](https://photoprism.app/kb/metadata)：
_注意：PhotoPrism会自动剔除关键词中的数字_
![image](https://user-images.githubusercontent.com/45256288/201001856-46bda27c-71df-4dff-8869-76ba8a8db084.png)

但在「标签」里没有：
![image](https://user-images.githubusercontent.com/45256288/201002124-856bbff0-8cfa-471e-a490-7c8c9efdf22e.png)

### PhotoPrism预期结果

标签”预期的效果“如下，「source」列「keyword」
![](https://docs.photoprism.app/user-guide/organize/img/remove-label-1-light.png)

**不确定**是否真的有这个功能，还是说keywords添加的有问题（逗号分割也不行👉`Keywords                        : NovelAIDiffusion,NovelAI`），文档没找到相关说明，上图来自[官方文档](https://docs.photoprism.app/user-guide/organize/labels/)

要不先不管，关键词也能起到索引的功能，可以直接搜索

2022-11-10 05:24 UTC, chu-shen commented
另外问一下，twitter这个api能加代理吗？

http(s)_proxy无效，现在是通过在docker里面部署 clash+iptables+proxychains 来连通的

2022-11-10 05:43 UTC, 15cm commented
PhotoPrism 的 label 默认我记得是用 ML 跑完自动加上去的，可能他们本来也没有想着从 keywords 里拿，我也没细看文档就是。

> 要不先不管，关键词也能起到索引的功能，可以直接搜索

我觉得可以。

2022-11-10 05:48 UTC, 15cm commented
代理我也没试过 ruby 脚本默认接受什么代理，http proxy 不行的话，一个思路是按照你的方式，不过是用 proxychains 指向 docker 外面的代理。比如加个环境变量指定代理的地址， socks5 或者 http(s) 都行，如果传了那个变量就用 proxychains 套一下那个 ruby 脚本。如果这个方式工作的话可以另开一个 PR

2022-11-10 06:16 UTC, chu-shen commented
> 代理我也没试过 ruby 脚本默认接受什么代理，http proxy 不行的话，一个思路是按照你的方式，不过是用 proxychains 指向 docker 外面的代理。比如加个环境变量指定代理的地址， socks5 或者 http(s) 都行，如果传了那个变量就用 proxychains 套一下那个 ruby 脚本。如果这个方式工作的话可以另开一个 PR

试过了，不行，不知道啥原因~~网络这块不熟~~，有可能是步骤有问题吧🤣

测试时的错误：
```log
null.rb:27:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello (OpenSSL::SSL::SSLError)

SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

2022-11-13 22:37 UTC, 15cm commented
那网络问题等你有想法了再单独开 issue 吧。你有空的时候看看 code review？

2022-11-14 02:35 UTC, chu-shen commented
> 那网络问题等你有想法了再单独开 issue 吧。你有空的时候看看 code review？

ok。已review

2022-11-14 05:51 UTC, 15cm commented
我这边没看到你的 review comment？https://github.com/15cm/twitter-favorites-archive/pull/3/files/77d522ba12f885eaeef4885c5faa69b34e13853b

2022-11-14 06:26 UTC, chu-shen reviewed
pr

2022-11-14 06:26 UTC, chu-shen commented
> 我这边没看到你的 review comment？https://github.com/15cm/twitter-favorites-archive/pull/3/files/77d522ba12f885eaeef4885c5faa69b34e13853b

可以了

2022-11-19 22:19 UTC, 15cm commented
我没有看到新的改动。请更新你的 PR （比如 https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request 的方式里选一个）然后在 review comment 底下回复你做的对应改动。

2022-11-20 03:36 UTC, chu-shen commented on docker/root/etc/cont-init.d/20-cron.sh
> +&& ./scripts/main.sh -tdmu -o ./output -c ./output/cache.txt >> /var/log/twitter-favorites-archive/stdout.log 2>&1'
调整定时任务日志输出

2022-11-20 03:58 UTC, chu-shen commented
> 我没有看到新的改动。请更新你的 PR （比如 https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request 的方式里选一个）然后在 review comment 底下回复你做的对应改动。

🥲没太懂，能不能说的再清楚一点，谢谢

是不是前面哪里误解了，一共就 4 commits，没有其他需要修改的。keywords能正常写入到图片元数据里，PhotoPrism也能正常读取到，只是其添加label的方式我不太清楚，所以目前没法直接将keywords添加为label

2022-11-20 05:50 UTC, 15cm requested changes

2022-11-20 05:50 UTC, 15cm commented on scripts/lib/download-media.sh
> +  elif grep -q '.mp4' <<< "${url}"; then
我的理解是你想要把视频和视频预览也下载下来，不打算改变图片的编号方式？我会建议：把视频这部份重新起一个 for-loop，因为视频你塞了两个 url 进去。多引入一个 `j`  做 ++/-- 这块代码很难维护。不想 copy-paste 下面下载部分的代码可以单独写个函数

2022-11-20 05:50 UTC, 15cm commented on docker/root/etc/cont-init.d/20-cron.sh
> +'echo "Archiving -- \$(date)" > /var/log/twitter-favorites-archive/stdout.log \
这边应该不需要转义？我检查了下我的 log，$(date) 是被替换成了日期的

2022-11-20 05:52 UTC, 15cm commented
啊非常抱歉，我的 comment 之前在草稿里没有发出去。GitHub 这个 UI 太迷惑了，我以为 comment 已经发出去了。

2022-11-20 12:10 UTC, chu-shen commented on docker/root/etc/cont-init.d/20-cron.sh
> +'echo "Archiving -- \$(date)" > /var/log/twitter-favorites-archive/stdout.log \
这里是写入到crontab前就被替换了，就像`${CRON_SCHEDULE}`一样。所以需要转义下

2022-11-20 12:10 UTC, chu-shen commented on scripts/lib/download-media.sh
> +  elif grep -q '.mp4' <<< "${url}"; then
这块主要是满足PhotoPrism的堆叠功能要求：文件同名（具体见https://docs.photoprism.app/user-guide/organize/stacks/）。

我这里的处理方式是：
1. 获取视频和其预览图的url，url顺序是：视频url+预览图url
2. 处理视频url后，下一个url必定是其预览图，所以引入`j`变量来重新编号，保证两个文件名相同

暂时没想到其他让视频和预览图文件名相同的处理方法

2022-11-22 10:56 UTC, chu-shen commented
> 1. 添加了更多元数据信息。不知道是不是keywords添加错了，PhotoPrism并没有自动添加为标签🥲

关键词转标签的正确方法👉https://github.com/photoprism/photoprism/discussions/998#discussioncomment-449679

其他信息：

- 讨论：[Labels: Option to automatically create labels for keywords coming from photo metadata (Exif/IPTC/XMP) · Issue #1143 · photoprism/photoprism · GitHub](https://github.com/photoprism/photoprism/issues/1143)
- Python API实现：[GitHub - dominikholler/photoprism-python-sdk](https://github.com/dominikholler/photoprism-python-sdk)

2022-11-23 10:15 UTC, chu-shen commented
已拆分url，现在支持下载gif视频

2022-11-23 10:23 UTC, chu-shen commented on scripts/lib/download-media.sh
> +  elif grep -q '.mp4' <<< "${url}"; then
> 这块主要是满足PhotoPrism的堆叠功能要求：文件同名（具体见[https://docs.photoprism.app/user-guide/organize/stacks/）。](https://docs.photoprism.app/user-guide/organize/stacks/%EF%BC%89%E3%80%82)

补充下：
1. 因为PhotoPrism不支持从视频直接提取描述、关键词等等元数据信息，所以在下载视频时同时下载其预览图并写入元数据信息。
2. 由于PhotoPrism的堆叠功能，视频和预览图被视为”同一个文件“，可以共享元数据信息

2022-11-26 00:18 UTC, 15cm commented on docker/root/etc/cont-init.d/20-cron.sh
> +'echo "Archiving -- \$(date)" > /var/log/twitter-favorites-archive/stdout.log \
单引号里面是不会替换的，bash -c 里看到的会是 `echo "Archiving -- $(date)"` 而非 `echo "Archiving -- Fri Nov 25 HH:MM:SS PM tz 2022"`。你可以本地用 shell 跑 echo ' "Archiving -- $(date)" '` 看一下。

2022-11-26 00:42 UTC, 15cm commented on scripts/lib/download-media.sh
> +  elif grep -q '.mp4' <<< "${url}"; then
ok，明白了这个处理还是针对视频+预览的。你 `elif .type == "video" then (.video_info.variants | max_by(.bitrate) | .url) + "\n" + "\(.media_url_https)?format=jpg&name=large"` 提取出来的的 url 只是数组里的一个元素，复现代码：
```
urls=('a.mp4\nb.jpg')
for ((i=0; i<${#urls[@]}; i++)); do echo ${urls[$i]}; done
```
output: `a.mp4\nb.jpg`

正确的做法是在 for loop 里检查当前 url 是否用 '\n'，然后在这个条件里一次性处理掉 '\n' 前面和后面的视频和预览链接，不需要维护一个 `j` 变量。

另外上面的 `if grep -q 'name=large' <<< "${url}"; then` 得排除掉视频+预览的情况，或者把视频+预览的条件放到最上面。

原则是把「单独有图片」和「视频+预览图」的情况分开处理。

2022-11-26 01:01 UTC, 15cm commented on scripts/lib/download-media.sh
> +      ((media_num--))
才看到新的 commit，和 https://github.com/15cm/twitter-favorites-archive/pull/3#discussion_r1032717831 一样的建议：for loop 应该把 mp4+'\n'+jpg 赋值给同一个循环的 url，然后把这个 url 变量拆成两个真正的 https 链接处理。`((media_num--))` 的代码依赖了整个 urls 数组的结构，很难维护。

2022-11-26 01:02 UTC, 15cm commented on scripts/lib/download-media.sh
> +mapfile -t photo_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "photo" then "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
`< <` 的作用是？我的理解应该是 `<<<` 来读 stdin？

2022-11-26 01:09 UTC, 15cm commented on scripts/lib/download-media.sh
> +mapfile -t photo_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "photo" then "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
为什么要选择换成 mapfile 而不用原来把命令 output 赋值给数组的方式呢？

2022-11-26 02:25 UTC, chu-shen commented on docker/root/etc/cont-init.d/20-cron.sh
> +'echo "Archiving -- \$(date)" > /var/log/twitter-favorites-archive/stdout.log \
你在docker里检查并执行下`20-cron.sh`呢，我这边不添加转义的话就会直接输出日期

2022-11-26 02:32 UTC, chu-shen commented on scripts/lib/download-media.sh
> +mapfile -t photo_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "photo" then "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
拆分媒体类型时顺便处理了，详细内容见ShellCheck：https://www.shellcheck.net/wiki/SC2207

2022-11-26 03:01 UTC, chu-shen commented on scripts/lib/download-media.sh
> +      ((media_num--))
这里`\n`已把视频和预览图划分成两行，urls变量里已经没有`\n`，结果来说是没有问题的：
```shell
# ./test.sh
url:
https://video.twimg.com/ext_tw_video/1594725902704943105/pu/vid/720x900/2FVzFFyrRwEQmTxT.mp4?tag=12
url:
https://pbs.twimg.com/ext_tw_video_thumb/1594725902704943105/pu/img/nfy2jFulx65qzGZs.jpg?format=jpg&name=large
# cat test.sh
#!/bin/bash
download_media() {
  for url in "$@"; do
          echo "url:"
          echo $url
  done
}
file=tweet.json
mapfile -t video_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "video" then (.video_info.variants | max_by(.bitrate) | .url) + "\n" + "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
download_media "${video_urls[@]}"
```

---

通过`((media_num--))`实现视频及其预览图有相同文件名，目前没别的思路。有更好的实现方法可以直接向这个pr提交新的commit

2022-12-01 04:45 UTC, 15cm commented on docker/root/etc/cont-init.d/20-cron.sh
> +'echo "Archiving -- \$(date)" > /var/log/twitter-favorites-archive/stdout.log \
你是对的。我试了一下也是一样。才想起来整个部分在 heredoc 里

2022-12-01 04:46 UTC, 15cm commented on scripts/lib/download-media.sh
> +      ((media_num--))
拆分文件类型以后这样写也 ok。我会自己加个 commit 让每个函数维护一个 local variable。

2022-12-01 04:52 UTC, 15cm commented on scripts/lib/download-media.sh
> +      ((media_num--))
在另一个回复里回复了这块代码。如你建议我会自己修改一下 `download_media` 来减少全局变量的影响范围。

2022-12-01 04:52 UTC, 15cm commented on scripts/lib/download-media.sh
> +mapfile -t photo_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "photo" then "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
https://stackoverflow.com/questions/29665142/bash-syntax-mapfile-input-redirection

2022-12-01 04:53 UTC, 15cm commented on scripts/lib/download-media.sh
> +mapfile -t photo_urls < <(jq -r '.extended_entities.media // [] | map(if .type == "photo" then "\(.media_url_https)?format=jpg&name=large" else empty end) | .[]' "$file")
thx. TIL

2022-12-01 04:54 UTC, 15cm approved these changes

2022-12-01 04:55 UTC, merged

2022-12-01 04:55 UTC, 15cm commented
已合并。感谢耐心回复 review comments。